def get_dummy_data():
    return {'name': 'APP0000068', 'uen': '', 'signature': '', 'company_status': 'Transferred In',
            'company_name': 'TEST COMPANY 2 PTE. LTD.', 'alt_company_name': 'TEST COMPANY 3 PTE. LTD.',
            'registration_no': '', 'incorporation_date': '', 'incorporate_type': 'Exempt Private Company',
            'financial_year_end': '25/08/2024', 'primary_activity_no': '01111',
            'primary_activity_name': 'Growing of leafy and fruit vegetables', 'secondary_activity_no': '01113',
            'secondary_activity_name': 'Growing of root crops', 'transfer_in': '', 'transfer_out': '',
            'date_striking': '', 'effect_date': '08/19/2023', 'addr_1': '111 SOMERSET ROAD #06-07',
            'addr_2': '111 SOMERSET SINGAPORE', 'postcode': '238164', 'full_name': 'Hussnain Ali',
            'mobile_no': '03080491287', 'phone': '03080491287', 'email': 'ahmadhussnain212@gmail.com', 'memo': '',
            'officers': [{'name': 'a406934802', 'full_name': 'AHSAN SARFRAZ', 'former_full_name': '', 'director': True,
                          'shareholder': True, 'secretary': False, 'designation': 'DIRECTOR / SHAREHOLDER',
                          'id_type': 'NRIC (Citizen)', 'id_number': 'SG-4564564564', 'gender': 'Male',
                          'dob': '01/01/1991', 'nationality': 'SINGAPOREAN', 'country_birth': 'PAKISTAN',
                          'address_1': 'STREET NO 123', 'address_2': 'STREET NO 456', 'postal_code': '54000',
                          'shareholder_share': '1', 'shareholder_certificate_number': '', 'allotment_date': '',
                          'signature': '', 'email': 'AHMADHUSSNAIN787@GMAIL.COM', 'mobile': '03086561801',
                          'remark': ''},
                         {'name': 'afe1ca57b9', 'full_name': 'AHMAD HUSSNAIN', 'former_full_name': '', 'director': True,
                          'shareholder': False, 'secretary': False, 'designation': 'DIRECTOR',
                          'id_type': 'NRIC (Citizen)', 'id_number': 'SG-4564564564', 'gender': 'Male',
                          'dob': '01/01/1991', 'nationality': 'SINGAPOREAN', 'country_birth': 'PAKISTAN',
                          'address_1': 'STREET NO 123', 'address_2': 'STREET NO 456', 'postal_code': '54000',
                          'shareholder_share': '1', 'shareholder_certificate_number': '', 'allotment_date': '',
                          'signature': '', 'email': 'AHMADHUSSNAIN787@GMAIL.COM', 'mobile': '03086561801',
                          'remark': ''}], 'officers_directors': [
            {'name': 'a406934802', 'full_name': 'AHSAN SARFRAZ', 'former_full_name': '', 'director': True,
             'shareholder': True, 'secretary': False, 'designation': 'DIRECTOR / SHAREHOLDER',
             'id_type': 'NRIC (Citizen)', 'id_number': 'SG-4564564564', 'gender': 'Male', 'dob': '01/01/1991',
             'nationality': 'SINGAPOREAN', 'country_birth': 'PAKISTAN', 'address_1': 'STREET NO 123',
             'address_2': 'STREET NO 456', 'postal_code': '54000', 'shareholder_share': '1',
             'shareholder_certificate_number': '', 'allotment_date': '', 'signature': '',
             'email': 'AHMADHUSSNAIN787@GMAIL.COM', 'mobile': '03086561801', 'remark': ''},
            {'name': 'afe1ca57b9', 'full_name': 'AHMAD HUSSNAIN', 'former_full_name': '', 'director': True,
             'shareholder': False, 'secretary': False, 'designation': 'DIRECTOR', 'id_type': 'NRIC (Citizen)',
             'id_number': 'SG-4564564564', 'gender': 'Male', 'dob': '01/01/1991', 'nationality': 'SINGAPOREAN',
             'country_birth': 'PAKISTAN', 'address_1': 'STREET NO 123', 'address_2': 'STREET NO 456',
             'postal_code': '54000', 'shareholder_share': '1', 'shareholder_certificate_number': '',
             'allotment_date': '', 'signature': '', 'email': 'AHMADHUSSNAIN787@GMAIL.COM', 'mobile': '03086561801',
             'remark': ''}], 'officers_shareholders': [
            {'name': 'a406934802', 'full_name': 'AHSAN SARFRAZ', 'former_full_name': '', 'director': True,
             'shareholder': True, 'secretary': False, 'designation': 'DIRECTOR / SHAREHOLDER',
             'id_type': 'NRIC (Citizen)', 'id_number': 'SG-4564564564', 'gender': 'Male', 'dob': '01/01/1991',
             'nationality': 'SINGAPOREAN', 'country_birth': 'PAKISTAN', 'address_1': 'STREET NO 123',
             'address_2': 'STREET NO 456', 'postal_code': '54000', 'shareholder_share': '1',
             'shareholder_certificate_number': '', 'allotment_date': '', 'signature': '',
             'email': 'AHMADHUSSNAIN787@GMAIL.COM', 'mobile': '03086561801', 'remark': ''}], 'officers_secretaries': [],
            'total_officers': 2, 'total_directors': 2, 'total_shareholders': 1, 'total_secretaries': 0,
            'capital_currency': '', 'no_issue_share': '0', 'each_share_price': '0.0'}
